// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

// User holds the schema definition for the User entity.
type User struct {
	ent.Schema
}

// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{field.Int32("id").Comment("数据表自增ID"), field.String("name").Comment("用户名"), field.String("email").

		// Edges of the User.
		Comment("邮箱"), field.String("mobile").Comment("手机号"), field.Bool("status").Comment("状态"), field.Time("created_at").Comment("添加时间"), field.Time("updated_at").Comment("修改时间"), field.Time("deleted_at").Optional().Comment("删除时间"), field.String("uuid").Comment("用户唯一标识")}

}

func (User) Edges() []ent.Edge {

	return nil
}
func (User) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "user"}}
}
